name: cln_grpc
description: A dart library which facilitates dart GRPC client for core lightning.
version: 0.0.1-beta.3
homepage: https://github.com/dart-lightning/lndart.cln_grpc

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  grpc: ^3.0.2
  protobuf: ^2.0.1
  cln_common: ^0.0.1-beta.1
  fixnum: ^1.0.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  clightning_rpc: ^0.0.2-beta.1
