/// TODO: add some docs here
library cln_grpc;

export 'src/cln_grpc_base.dart';

// autogenerated file!
export 'src/generated/node.pb.dart';
export 'src/generated/node.pbgrpc.dart';
export 'src/generated/primitives.pb.dart';
export 'src/generated/primitives.pbgrpc.dart';
